version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.12"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --extra docs
    - cd docs; uv run make
